mm-memcontrol-rewrite-uncharge-api-fix
kernel/events/uprobes.c: In function 'uprobe_write_opcode':
kernel/events/uprobes.c:328: error: implicit declaration of function 'mem_cgroup_uncharge_page'
kernel/events/uprobes.c:330: warning: label 'put_new' defined but not used

bodge this so it compiles

Cc: Hugh Dickins <hughd@google.com>
Cc: Johannes Weiner <hannes@cmpxchg.org>
Cc: Michal Hocko <mhocko@suse.cz>
Cc: Tejun Heo <tj@kernel.org>
Cc: Vladimir Davydov <vdavydov@parallels.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>