drivers/infiniband/hw/cxgb4/device.c: fix 32-bit builds
ERROR: "__udivdi3" [drivers/infiniband/hw/cxgb4/iw_cxgb4.ko] undefined!

Fixes 7730b4c7e32c0ab4d ("cxgb4/iw_cxgb4: work request logging feature").

Cc: Hariprasad Shenai <hariprasad@chelsio.com>
Cc: Steve Wise <swise@opengridcomputing.com>
Cc: David Miller <davem@davemloft.net>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>