mm-introduce-common-page-state-for-ballooned-memory-fix
export __ClearPageBalloon() and __SetPageBalloon() to modules

ERROR: "__ClearPageBalloon" [drivers/virtio/virtio_balloon.ko] undefined!
ERROR: "__SetPageBalloon" [drivers/virtio/virtio_balloon.ko] undefined!

Cc: Andrey Ryabinin <ryabinin.a.a@gmail.com>
Cc: Konstantin Khlebnikov <k.khlebnikov@samsung.com>
Cc: Rafael Aquini <aquini@redhat.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>