mm-memcontrol-rewrite-charge-api-fix
kernel/events/uprobes.c: In function 'uprobe_write_opcode':
kernel/events/uprobes.c:319: error: implicit declaration of function 'mem_cgroup_charge_anon'

bodge things so it compiles

Cc: Hugh Dickins <hughd@google.com>
Cc: Johannes Weiner <hannes@cmpxchg.org>
Cc: Michal Hocko <mhocko@suse.cz>
Cc: Tejun Heo <tj@kernel.org>
Cc: Vladimir Davydov <vdavydov@parallels.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>