headers: prctl.h -- Add missing linux/types.h
Stephen reported:

 | After merging the akpm-current tree, today's linux-next build (x86_64
 | allmodconfig) failed like this:
 |
 | ./usr/include/linux/prctl.h:132: found __[us]{8,16,32,64} type without #include <linux/types.h>
 | In file included from /usr/include/x86_64-linux-gnu/sys/prctl.h:23:0,
 |                 from Documentation/prctl/disable-tsc-test.c:14:
 | ./usr/include/linux/prctl.h:132:2: error: unknown type name '__u64'
 |

Include the header needed.

Signed-off-by: Cyrill Gorcunov <gorcunov@openvz.org>
Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>