common: dma-mapping: Protect remapping functions with CONFIG_MMU
The dma remapping functions use vmalloc features which are
not defined for CONFIG_MMU=n

drivers/built-in.o: In function `dma_common_pages_remap':
  drivers/base/dma-mapping.c:311: undefined reference to `get_vm_area_caller'
  drivers/base/dma-mapping.c:315: undefined reference to `map_vm_area'
drivers/built-in.o: In function `dma_common_free_remap':
  drivers/base/dma-mapping.c:328: undefined reference to `find_vm_area'

These functions aren't applicable for nommu targets so protect them
with #ifdef CONFIG_MMU

Signed-off-by: Laura Abbott <lauraa@codeaurora.org>
Reported-by: kbuild test robot <fengguang.wu@intel.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>